In [5]:
import pandas as pd
df = pd.read_csv("air_quality_historical.csv")

In [6]:
df

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,us_aqi,european_aqi
0,2022-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-08-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-08-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-08-04,27.152632,18.984211,328.157895,13.226316,5.373684,75.526316,0.491053,0.421053,2.094737,NaN,NaN
4,2022-08-05,15.529167,10.879167,237.875000,13.645833,6.395833,52.833333,0.221667,0.000000,1.066667,55.315789,29.157895
...,...,...,...,...,...,...,...,...,...,...,...,...
1293,2026-02-14,50.154167,48.300000,673.416667,10.266667,14.766667,127.916667,0.460833,2.875000,1.810417,125.416667,75.708333
1294,2026-02-15,62.729167,60.625000,845.750000,15.004167,15.500000,126.958333,0.678333,3.625000,1.735417,144.166667,82.500000
1295,2026-02-16,70.454167,68.583333,687.208333,13.158333,15.329167,130.000000,0.698750,3.208333,1.702083,156.500000,94.250000
1296,2026-02-17,51.379167,50.233333,552.916667,7.229167,12.458333,127.333333,0.540833,1.916667,1.879167,150.250000,87.250000
1297,2026-02-18,43.029167,41.875000,540.666667,6.883333,11.441667,123.666667,0.430417,1.625000,1.975000,124.083333,75.916667

In [7]:
df.shape

(1298, 12)

In [8]:
df.info

<bound method DataFrame.info of             date       pm10      pm2_5  carbon_monoxide  nitrogen_dioxide  \
0     2022-08-01        NaN        NaN              NaN               NaN
1     2022-08-02        NaN        NaN              NaN               NaN
2     2022-08-03        NaN        NaN              NaN               NaN
3     2022-08-04  27.152632  18.984211       328.157895         13.226316
4     2022-08-05  15.529167  10.879167       237.875000         13.645833
...          ...        ...        ...              ...               ...
1293  2026-02-14  50.154167  48.300000       673.416667         10.266667
1294  2026-02-15  62.729167  60.625000       845.750000         15.004167
1295  2026-02-16  70.454167  68.583333       687.208333         13.158333
1296  2026-02-17  51.379167  50.233333       552.916667          7.229167
1297  2026-02-18  43.029167  41.875000       540.666667          6.883333

      sulphur_dioxide       ozone  aerosol_optical_depth      dust  uv_index  \
0                 NaN         NaN                    NaN       NaN       NaN
1                 NaN         NaN                    NaN       NaN       NaN
2                 NaN         NaN                    NaN       NaN       NaN
3            5.373684   75.526316               0.491053  0.421053  2.094737
4            6.395833   52.833333               0.221667  0.000000  1.066667
...               ...         ...                    ...       ...       ...
1293        14.766667  127.916667               0.460833  2.875000  1.810417
1294        15.500000  126.958333               0.678333  3.625000  1.735417
1295        15.329167  130.000000               0.698750  3.208333  1.702083
1296        12.458333  127.333333               0.540833  1.916667  1.879167
1297        11.441667  123.666667               0.430417  1.625000  1.975000

          us_aqi  european_aqi
0            NaN           NaN
1            NaN           NaN
2            NaN           NaN
3            NaN           NaN
4      55.315789     29.157895
...          ...           ...
1293  125.416667     75.708333
1294  144.166667     82.500000
1295  156.500000     94.250000
1296  150.250000     87.250000
1297  124.083333     75.916667

[1298 rows x 12 columns]>

In [9]:
print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Dataset Shape:
(1298, 12)

Column Names:
['date', 'pm10', 'pm2_5', 'carbon_monoxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone', 'aerosol_optical_depth', 'dust', 'uv_index', 'us_aqi', 'european_aqi']

Data Types:
date                      object
pm10                     float64
pm2_5                    float64
carbon_monoxide          float64
nitrogen_dioxide         float64
sulphur_dioxide          float64
ozone                    float64
aerosol_optical_depth    float64
dust                     float64
uv_index                 float64
us_aqi                   float64
european_aqi             float64
dtype: object

Missing Values:
date                     0
pm10                     3
pm2_5                    3
carbon_monoxide          3
nitrogen_dioxide         3
sulphur_dioxide          3
ozone                    3
aerosol_optical_depth    3
dust                     3
uv_index                 3
us_aqi                   4
european_aqi             4
dtype: int64

Duplicate Rows:
0

In [10]:
df['date'] = pd.to_datetime(df['date'])

In [11]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [12]:
print(df.isnull().sum())

date                     0
pm10                     3
pm2_5                    3
carbon_monoxide          3
nitrogen_dioxide         3
sulphur_dioxide          3
ozone                    3
aerosol_optical_depth    3
dust                     3
uv_index                 3
us_aqi                   4
european_aqi             4
dtype: int64

In [13]:
df[df.isnull().any(axis=1)]

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,us_aqi,european_aqi
0,2022-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-08-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-08-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-08-04,27.152632,18.984211,328.157895,13.226316,5.373684,75.526316,0.491053,0.421053,2.094737,NaN,NaN

In [19]:
pollutant_columns = [
    'pm10',
    'pm2_5',
    'carbon_monoxide',
    'nitrogen_dioxide',
    'sulphur_dioxide',
    'ozone'
]

print(df[pollutant_columns].isnull().sum())

pm10                0
pm2_5               0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
dtype: int64

In [20]:
df.head

<bound method NDFrame.head of            date       pm10      pm2_5  carbon_monoxide  nitrogen_dioxide  \
0    2022-08-07   8.245833   5.758333       170.166667          8.783333
1    2022-08-08   6.725000   4.716667       160.833333          7.508333
2    2022-08-09   7.120833   4.866667       148.166667          6.470833
3    2022-08-10  11.904167   7.625000       147.333333          6.283333
4    2022-08-11  10.012500   6.625000       149.083333          6.425000
...         ...        ...        ...              ...               ...
1287 2026-02-14  50.154167  48.300000       673.416667         10.266667
1288 2026-02-15  62.729167  60.625000       845.750000         15.004167
1289 2026-02-16  70.454167  68.583333       687.208333         13.158333
1290 2026-02-17  51.379167  50.233333       552.916667          7.229167
1291 2026-02-18  43.029167  41.875000       540.666667          6.883333

      sulphur_dioxide       ozone  aerosol_optical_depth      dust  uv_index  \
0            2.958333   42.250000               0.103333  0.000000  1.031250
1            2.841667   42.083333               0.061250  0.000000  1.137500
2            3.037500   46.958333               0.129167  0.500000  1.591667
3            3.841667   52.666667               0.216667  2.875000  1.670833
4            5.262500   48.333333               0.212500  1.458333  2.054167
...               ...         ...                    ...       ...       ...
1287        14.766667  127.916667               0.460833  2.875000  1.810417
1288        15.500000  126.958333               0.678333  3.625000  1.735417
1289        15.329167  130.000000               0.698750  3.208333  1.702083
1290        12.458333  127.333333               0.540833  1.916667  1.879167
1291        11.441667  123.666667               0.430417  1.625000  1.975000

          us_aqi  european_aqi
0      27.833333     17.250000
1      21.916667     16.791667
2      22.208333     18.750000
3      24.791667     20.916667
4      33.500000     19.791667
...          ...           ...
1287  125.416667     75.708333
1288  144.166667     82.500000
1289  156.500000     94.250000
1290  150.250000     87.250000
1291  124.083333     75.916667

[1292 rows x 12 columns]>

In [21]:
df[pollutant_columns] = df[pollutant_columns].interpolate()
df[pollutant_columns] = df[pollutant_columns].ffill().bfill()
print(df[pollutant_columns].isnull().sum())

pm10                0
pm2_5               0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
dtype: int64

In [22]:
print((df[pollutant_columns] < 0).sum())

pm10                0
pm2_5               0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
dtype: int64

In [23]:
print("Shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicates:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Shape: (1292, 12)

Missing values:
date                     0
pm10                     0
pm2_5                    0
carbon_monoxide          0
nitrogen_dioxide         0
sulphur_dioxide          0
ozone                    0
aerosol_optical_depth    0
dust                     0
uv_index                 0
us_aqi                   0
european_aqi             0
dtype: int64

Duplicates: 0

Data types:
date                     datetime64[ns]
pm10                            float64
pm2_5                           float64
carbon_monoxide                 float64
nitrogen_dioxide                float64
sulphur_dioxide                 float64
ozone                           float64
aerosol_optical_depth           float64
dust                            float64
uv_index                        float64
us_aqi                          float64
european_aqi                    float64
dtype: object

In [24]:
pollutant_columns = [
    'pm10',
    'pm2_5',
    'carbon_monoxide',
    'nitrogen_dioxide',
    'sulphur_dioxide',
    'ozone'
]

In [25]:
pm25_breakpoints = [
    (0.0, 9.0, 0, 50),
    (9.1, 35.4, 51, 100),
    (35.5, 55.4, 101, 150),
    (55.5, 125.4, 151, 200),
    (125.5, 225.4, 201, 300),
    (225.5, 325.4, 301, 500)
]

In [26]:
def calculate_aqi(C, breakpoints):

    for Clow, Chigh, Ilow, Ihigh in breakpoints:

        if Clow <= C <= Chigh:

            AQI = ((Ihigh - Ilow) / (Chigh - Clow)) * \
                  (C - Clow) + Ilow

            return AQI

    return np.nan

In [27]:
calculate_aqi(40, pm25_breakpoints)

112.08040201005025

In [29]:
import numpy as np

In [30]:
df['pm2_5_aqi'] = df['pm2_5'].apply(
    lambda x: calculate_aqi(x, pm25_breakpoints)
)

In [31]:
print(df[['pm2_5', 'pm2_5_aqi']].head())

      pm2_5  pm2_5_aqi
0  5.758333  31.990741
1  4.716667  26.203704
2  4.866667  27.037037
3  7.625000  42.361111
4  6.625000  36.805556

In [32]:
pm10_breakpoints = [
    (0, 54, 0, 50),
    (55, 154, 51, 100),
    (155, 254, 101, 150),
    (255, 354, 151, 200),
    (355, 424, 201, 300),
    (425, 504, 301, 500)
]
df['pm10_aqi'] = df['pm10'].apply(
    lambda x: calculate_aqi(x, pm10_breakpoints)
)

In [33]:
print(df[['pm10', 'pm10_aqi']].head())

        pm10   pm10_aqi
0   8.245833   7.635031
1   6.725000   6.226852
2   7.120833   6.593364
3  11.904167  11.022377
4  10.012500   9.270833

In [34]:
co_breakpoints = [
    (0.0, 4.4, 0, 50),
    (4.5, 9.4, 51, 100),
    (9.5, 12.4, 101, 150),
    (12.5, 15.4, 151, 200),
    (15.5, 30.4, 201, 300),
    (30.5, 50.4, 301, 500)
]
df['co_aqi'] = df['carbon_monoxide'].apply(
    lambda x: calculate_aqi(x, co_breakpoints)
)
print(df[['carbon_monoxide', 'co_aqi']].head())

   carbon_monoxide  co_aqi
0       170.166667     NaN
1       160.833333     NaN
2       148.166667     NaN
3       147.333333     NaN
4       149.083333     NaN

In [35]:
print(df['carbon_monoxide'].describe())

count    1292.000000
mean      429.821530
std       193.812665
min        59.041667
25%       277.718750
50%       413.604167
75%       547.385417
max      1554.833333
Name: carbon_monoxide, dtype: float64

In [36]:
print(df['carbon_monoxide'].head())

0    170.166667
1    160.833333
2    148.166667
3    147.333333
4    149.083333
Name: carbon_monoxide, dtype: float64

In [37]:
print(df[['carbon_monoxide', 'pm2_5', 'pm10']].head())

   carbon_monoxide     pm2_5       pm10
0       170.166667  5.758333   8.245833
1       160.833333  4.716667   6.725000
2       148.166667  4.866667   7.120833
3       147.333333  7.625000  11.904167
4       149.083333  6.625000  10.012500

In [39]:
no2_breakpoints = [
    (0, 53, 0, 50),
    (54, 100, 51, 100),
    (101, 360, 101, 150),
    (361, 649, 151, 200),
    (650, 1249, 201, 300),
    (1250, 2049, 301, 500)
]
df['no2_ppb'] = df['nitrogen_dioxide'] * 24.45 / 46.0055
df['no2_aqi'] = df['no2_ppb'].apply(
    lambda x: calculate_aqi(x, no2_breakpoints)
)
print(df[['nitrogen_dioxide', 'no2_ppb', 'no2_aqi']].head())

   nitrogen_dioxide   no2_ppb   no2_aqi
0          8.783333  4.667974  4.403750
1          7.508333  3.990365  3.764496
2          6.470833  3.438977  3.244318
3          6.283333  3.339329  3.150310
4          6.425000  3.414619  3.221339

In [40]:
so2_breakpoints = [
    (0, 35, 0, 50),
    (36, 75, 51, 100),
    (76, 185, 101, 150),
    (186, 304, 151, 200),
    (305, 604, 201, 300),
    (605, 1004, 301, 500)
]
df['so2_ppb'] = df['sulphur_dioxide'] * 24.45 / 64.066
df['so2_aqi'] = df['so2_ppb'].apply(
    lambda x: calculate_aqi(x, so2_breakpoints)
)
print(df[['sulphur_dioxide', 'so2_ppb', 'so2_aqi']].head())

   sulphur_dioxide   so2_ppb   so2_aqi
0         2.958333  1.129011  1.612874
1         2.841667  1.084487  1.549267
2         3.037500  1.159224  1.656035
3         3.841667  1.466125  2.094464
4         5.262500  2.008368  2.869098

In [41]:
o3_breakpoints = [
    (0, 54, 0, 50),
    (55, 70, 51, 100),
    (71, 85, 101, 150),
    (86, 105, 151, 200),
    (106, 200, 201, 300),
    (201, 604, 301, 500)
]
df['o3_ppb'] = df['ozone'] * 24.45 / 47.9982
df['o3_aqi'] = df['o3_ppb'].apply(
    lambda x: calculate_aqi(x, o3_breakpoints)
)
print(df[['ozone', 'o3_ppb', 'o3_aqi']].head())

       ozone     o3_ppb     o3_aqi
0  42.250000  21.521901  19.927686
1  42.083333  21.437002  19.849076
2  46.958333  23.920298  22.148424
3  52.666667  26.828089  24.840824
4  48.333333  24.620715  22.796958

In [42]:
aqi_columns = [
    'pm2_5_aqi',
    'pm10_aqi',
    'co_aqi',
    'no2_aqi',
    'so2_aqi',
    'o3_aqi'
]
df['calculated_aqi'] = df[aqi_columns].max(axis=1)
print(df[aqi_columns + ['calculated_aqi']].head())

   pm2_5_aqi   pm10_aqi  co_aqi   no2_aqi   so2_aqi     o3_aqi  calculated_aqi
0  31.990741   7.635031     NaN  4.403750  1.612874  19.927686       31.990741
1  26.203704   6.226852     NaN  3.764496  1.549267  19.849076       26.203704
2  27.037037   6.593364     NaN  3.244318  1.656035  22.148424       27.037037
3  42.361111  11.022377     NaN  3.150310  2.094464  24.840824       42.361111
4  36.805556   9.270833     NaN  3.221339  2.869098  22.796958       36.805556

In [43]:
print(co_breakpoints)
print(df['carbon_monoxide'].min())
print(df['carbon_monoxide'].max())

[(0.0, 4.4, 0, 50), (4.5, 9.4, 51, 100), (9.5, 12.4, 101, 150), (12.5, 15.4, 151, 200), (15.5, 30.4, 201, 300), (30.5, 50.4, 301, 500)]
59.04166666666666
1554.8333333333333

In [44]:
df['co_ppm'] = df['carbon_monoxide'] * 24.45 / (28.01 * 1000)
df['co_aqi'] = df['co_ppm'].apply(
    lambda x: calculate_aqi(x, co_breakpoints)
)
print(df[['carbon_monoxide', 'co_ppm', 'co_aqi']].head())

   carbon_monoxide    co_ppm    co_aqi
0       170.166667  0.148539  1.687942
1       160.833333  0.140392  1.595362
2       148.166667  0.129335  1.469717
3       147.333333  0.128608  1.461450
4       149.083333  0.130135  1.478809

In [45]:
df['calculated_aqi'] = df[aqi_columns].max(axis=1)
print(df[aqi_columns + ['calculated_aqi']].head())

   pm2_5_aqi   pm10_aqi    co_aqi   no2_aqi   so2_aqi     o3_aqi  \
0  31.990741   7.635031  1.687942  4.403750  1.612874  19.927686
1  26.203704   6.226852  1.595362  3.764496  1.549267  19.849076
2  27.037037   6.593364  1.469717  3.244318  1.656035  22.148424
3  42.361111  11.022377  1.461450  3.150310  2.094464  24.840824
4  36.805556   9.270833  1.478809  3.221339  2.869098  22.796958

   calculated_aqi
0       31.990741
1       26.203704
2       27.037037
3       42.361111
4       36.805556

In [46]:
def classify_aqi(aqi):
    if aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Moderate"
    elif aqi <= 150:
        return "Poor"
    elif aqi <= 200:
        return "Severe"
    else:
        return "Very Severe"

In [55]:
df['aqi_category'] = df['calculated_aqi'].apply(classify_aqi)

In [56]:
print(df[['calculated_aqi', 'aqi_category']].head(10))

   calculated_aqi aqi_category
0       31.990741         Good
1       26.203704         Good
2       27.037037         Good
3       42.361111         Good
4       36.805556         Good
5       31.782407         Good
6       36.319444         Good
7       36.180556         Good
8       47.175926         Good
9       55.277408     Moderate

In [57]:
df

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,...,no2_ppb,no2_aqi,so2_ppb,so2_aqi,o3_ppb,o3_aqi,calculated_aqi,co_ppm,overall_aqi,aqi_category
0,2022-08-07,8.245833,5.758333,170.166667,8.783333,2.958333,42.250000,0.103333,0.000000,1.031250,...,4.667974,4.403750,1.129011,1.612874,21.521901,19.927686,31.990741,0.148539,31.990741,Good
1,2022-08-08,6.725000,4.716667,160.833333,7.508333,2.841667,42.083333,0.061250,0.000000,1.137500,...,3.990365,3.764496,1.084487,1.549267,21.437002,19.849076,26.203704,0.140392,26.203704,Good
2,2022-08-09,7.120833,4.866667,148.166667,6.470833,3.037500,46.958333,0.129167,0.500000,1.591667,...,3.438977,3.244318,1.159224,1.656035,23.920298,22.148424,27.037037,0.129335,27.037037,Good
3,2022-08-10,11.904167,7.625000,147.333333,6.283333,3.841667,52.666667,0.216667,2.875000,1.670833,...,3.339329,3.150310,1.466125,2.094464,26.828089,24.840824,42.361111,0.128608,42.361111,Good
4,2022-08-11,10.012500,6.625000,149.083333,6.425000,5.262500,48.333333,0.212500,1.458333,2.054167,...,3.414619,3.221339,2.008368,2.869098,24.620715,22.796958,36.805556,0.130135,36.805556,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1287,2026-02-14,50.154167,48.300000,673.416667,10.266667,14.766667,127.916667,0.460833,2.875000,1.810417,...,5.456304,5.147457,5.635516,8.050738,65.159996,84.189319,132.517588,0.587827,132.517588,Poor
1288,2026-02-15,62.729167,60.625000,845.750000,15.004167,15.500000,126.958333,0.678333,3.625000,1.735417,...,7.974087,7.522724,5.915384,8.450549,64.671826,82.594632,154.592632,0.738257,154.592632,Severe
1289,2026-02-16,70.454167,68.583333,687.208333,13.158333,15.329167,130.000000,0.698750,3.208333,1.702083,...,6.993104,6.597268,5.850188,8.357411,66.221233,87.656029,160.171435,0.599866,160.171435,Severe
1290,2026-02-17,51.379167,50.233333,552.916667,7.229167,12.458333,127.333333,0.540833,1.916667,1.879167,...,3.842000,3.624528,4.754570,6.792242,64.862849,83.218640,137.278057,0.482642,137.278057,Poor
1291,2026-02-18,43.029167,41.875000,540.666667,6.883333,11.441667,123.666667,0.430417,1.625000,1.975000,...,3.658204,3.451136,4.366571,6.237959,62.995071,77.117231,116.697236,0.471949,116.697236,Poor